version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: Web4U-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: default
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - cat4u-net

    redis:
        image: redis:7.2-alpine
        container_name: Web4U-redis
        restart: unless-stopped
        ports:
            - "127.0.0.1:6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        networks:
            - cat4u-net

volumes:
    mysql_data:

networks:
    cat4u-net:
        driver: bridge
