blank_issues_enabled: false
issue_templates:
  - name: ğŸ§© Task
    description: ë§¡ì€ ê¸°ëŠ¥ì„ êµ¬í˜„í•  ë•Œ ì‚¬ìš©í•˜ëŠ” ê¸°ë³¸ ì‘ì—… ì´ìŠˆ
    labels: [task]
    file: task.md

  - name: ğŸ Bug
    description: ë°œê²¬ëœ ë¬¸ì œë‚˜ ì˜¤ë¥˜ ë³´ê³ 
    labels: [bug]
    file: bug.md

  - name: ğŸ§¹ Refactoring
    description: ì½”ë“œ ê°œì„ /ë¦¬íŒ©í„°ë§ ì‘ì—… ìš”ì²­
    labels: [refactor]
    file: refactoring.md

  - name: âœ¨ Feature Suggestion
    description: ê¸°ëŠ¥ ì¶”ê°€/ê°œì„  ì•„ì´ë””ì–´ ì œì•ˆ
    labels: [enhancement]
    file: feature_suggestion.md

  - name: ğŸ“„ Documentation
    description: ë¬¸ì„œ ì‘ì„±/ìˆ˜ì • ê´€ë ¨ ì‘ì—…
    labels: [documentation]
    file: documentation.md
